* Preface
- I'm not a coder. Therefore the configuration is not geared towards that.
- I'm on windows and on a slow pc. Therefore packages that are not working fast on windows (i.e. because they use extensive process-forking - which is non existent on windows) are not used no matter how useful they might be. Also some packages do not work properly because they use (on windows) not properly implemented backends, like terminals and shells.
- I have a certain workflow, that involves the use of windows specfic apps, like windows-explorer. Because of that and things mentioned above some packages, although very useful by themself, have no use for me. Projectile would be one example.
- I try to be use packages that fit within the basic emacs concepts. Although emacs can be bend beyond recognicion doesn't mean I like that. So evil mode and helm are not for me.
- A word on spacemacs/prelude and similar emacs distributions. First especially spacemacs is geard towards vi users and programmers. Currently I don't want both. This stands symbol for the general problem with all preconfigured or micropreconfigured (Spacemacs-Layers) Emacs distributions - they contain a lot of stuff I don't need or want. This extra bloat causes slowdown. The second problem is that every package in emacs can fail or misbehave. This accumulates with the number of packages. Therefore IMHO the best option is to have a slim emacs only with packages that you need or at least understand their use. There might be users who can harness the advantages of these preconfigured emacs distributions and can live/deal with the problems that might occur, but I don't. Conclusion: Only use the preconfigured emacs distributions if you know what your dealing with.
* Code-Examples
** Latex
#+begin_src latex :file fsa.pdf :packages '(("" "tikz")) :border 1em
  % Define block styles
  \usetikzlibrary{shapes,arrows}
  \tikzstyle{astate} = [circle, draw, text centered, font=\footnotesize, fill=blue!25]
  \tikzstyle{rstate} = [circle, draw, text centered, font=\footnotesize, fill=red!25]

  \begin{tikzpicture}[->,>=stealth', shorten >=1pt, auto, node distance=2.8cm, semithick]
    \node [astate] (1) at (0,0) {1};
    \node [astate] (2) at (1,0) {2};
    \node [rstate] (3) at (2,0) {3};
    \path (1) edge [bend left] node {b} (2)
          (2) edge node {b} (3)
          (2) edge [bend left] node {a} (1)
          (3) edge [loop above] node {(a, b)} (3);
  \end{tikzpicture}
#+end_src
* External Text-Files
** Windows Example-Shortcuts
*** Client - not waiting for server, opening frame and starting as daemon if not yet done
emacsclientw.exe -n -c -a ""
*** Full Application in Debugging Mode
runemacs.exe -debug-init
*** Client - not waiting for server, opening frame and starting as daemon if not yet done, switching to temp buffer and adding a dated entry
emacsclientw.exe -n -c -a ""  -e "(my-timestamper-for-temp)" -F "((fullscreen . maximized))"
** Batch Files
Save as .bat files and execute where needed
*** Convert .txt and .cfg Files to .org
REM Uses foldername as top level and filenames as secondary level
for %%* in (.) do (echo * %%~nx* >> output.org)
for /r %%i in (*.txt) (*.cfg) do (
if not %%~nxi == output.org (
echo ** %%~nxi >> output.org
type "%%i" >> output.org
echo. >> output.org
)
)
** Compile-example of pdf-tools-installation
#+BEGIN_SRC browser :out pdf-tools.png
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<!-- Created by htmlize-1.54 in css mode. -->
<html>
  <head>
    <title>*compilation*</title>
    <style type="text/css">
    <!--
      body {
        color: #ffffff;
        background-color: #000000;
      }
      .comint-highlight-input {
        /* comint-highlight-input */
        font-weight: bold;
      }
      .comint-highlight-prompt {
        /* comint-highlight-prompt */
        color: #b4fa70;
      }
      .comint-highlight-prompt {
        /* comint-highlight-prompt */
        color: #b4fa70;
      }
      .compilation-line-number {
        /* compilation-line-number */
        color: #b4fa70;
      }
      .function-name {
        /* font-lock-function-name-face */
        color: #fce94f;
      }

      a {
        color: inherit;
        background-color: inherit;
        font: inherit;
        text-decoration: inherit;
      }
      a:hover {
        text-decoration: underline;
      }
    -->
    </style>
  </head>
  <body>
    <pre>
J-*- mode: compilation; default-directory: "~/.emacs.d/elpa/pdf-tools-20180422.935/build/server/" -*-
Comint started at Tue Apr 24 03:41:34

c\:/\!Data/home/jlange/.emacs.d/elpa/pdf-tools-20180422.935/build/server/autobuild -i c\:/\!Software/Portable/Emacs/bin/
---------------------------
    Installing packages    
---------------------------
pacman -S --needed base-devel
                      mingw-w64-x86_64-libpng
                      mingw-w64-x86_64-poppler
                      mingw-w64-x86_64-toolchain
                      mingw-w64-x86_64-zlib
:: Es befinden sich 55 Mitglieder in Gruppe base-devel:
:: Repositorium msys

<span class="comint-highlight-prompt"><span class="comint-highlight-prompt">Geben Sie eine Auswahl ein (Voreinstellung=alle): </span></span>
<span class="function-name">Warnung</span>: asciidoc-8.6.9-4 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: autoconf-2.69-3 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: autoconf2.13-2.13-2 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: autogen-5.18.12-2 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: automake-wrapper-10-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: automake1.10-1.10.3-3 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: automake1.11-1.11.6-3 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: automake1.12-1.12.6-3 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: automake1.13-1.13.4-4 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: automake1.14-1.14.1-3 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: automake1.15-1.15.1-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: automake1.6-1.6.3-2 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: automake1.7-1.7.9-2 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: automake1.8-1.8.5-3 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: automake1.9-1.9.6-2 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: bison-3.0.4-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: diffstat-1.61-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: diffutils-3.5-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: dos2unix-7.4.0-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: file-5.33-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: flex-2.6.4-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: gawk-4.2.0-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: gdb-7.11.1-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: gettext-0.19.8.1-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: gettext-devel-0.19.8.1-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: gperf-3.1-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: grep-3.0-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: groff-1.22.3-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: help2man-1.47.5-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: intltool-0.51.0-2 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: lemon-3.8.7.0-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: libtool-2.4.6-2 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: libunrar-5.5.3-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: libunrar-devel-5.5.3-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: m4-1.4.18-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: make-4.2.1-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: man-db-2.7.6-3 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: pacman-5.0.1-5 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: pactoys-git-r2.07ca37f-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: patch-2.7.6-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: patchutils-0.3.4-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: perl-5.24.4-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: pkg-config-0.29.2-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: pkgfile-17-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: quilt-0.65-2 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: rcs-5.9.4-2 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: scons-2.5.1-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: sed-4.4-2 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: swig-3.0.12-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: texinfo-6.3-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: texinfo-tex-6.3-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: ttyrec-1.0.8-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: unrar-5.5.3-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: wget-1.19.4-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: xmlto-0.0.28-1 ist aktuell -- &#220;berspringe
   1) asciidoc  2) autoconf  3) autoconf2.13  4) autogen  5) automake-wrapper  6) automake1.10  7) automake1.11  8) automake1.12  9) automake1.13  10) automake1.14  11) automake1.15  12) automake1.6  13) automake1.7  14) automake1.8  15) automake1.9  16) bison  17) diffstat  18) diffutils  19) dos2unix  20) file  21) flex  22) gawk  23) gdb  24) gettext  25) gettext-devel  26) gperf  27) grep  28) groff  29) help2man  30) intltool  31) lemon  32) libtool  33) libunrar  34) libunrar-devel  35) m4  36) make  37) man-db  38) pacman  39) pactoys-git  40) patch  41) patchutils  42) perl  43) pkg-config  44) pkgfile  45) quilt  46) rcs  47) scons  48) sed  49) swig  50) texinfo  51) texinfo-tex  52) ttyrec  53) unrar  54) wget  55) xmlto
:: Es befinden sich 17 Mitglieder in Gruppe mingw-w64-x86_64-toolchain:
:: Repositorium mingw64

<span class="comint-highlight-prompt"><span class="comint-highlight-prompt">Geben Sie eine Auswahl ein (Voreinstellung=alle): </span></span>
<span class="function-name">Warnung</span>: mingw-w64-x86_64-binutils-2.30-2 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-crt-git-6.0.0.5125.b491fac6-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-gcc-7.3.0-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-gcc-ada-7.3.0-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-gcc-fortran-7.3.0-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-gcc-libgfortran-7.3.0-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-gcc-libs-7.3.0-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-gcc-objc-7.3.0-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-gdb-8.0.1-4 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-headers-git-6.0.0.5125.b491fac6-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-libmangle-git-6.0.0.5079.3b7a42fd-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-libwinpthread-git-6.0.0.5098.2464b7e6-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-make-4.2.1-2 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-pkg-config-0.29.2-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-tools-git-6.0.0.5111.3bc5ab74-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-winpthreads-git-6.0.0.5098.2464b7e6-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-winstorecompat-git-5.0.0.4760.d3089b5-1 ist aktuell -- &#220;berspringe
<span class="function-name">Warnung</span>: mingw-w64-x86_64-zlib-1.2.11-1 ist aktuell -- &#220;berspringe
   1) mingw-w64-x86_64-binutils  2) mingw-w64-x86_64-crt-git  3) mingw-w64-x86_64-gcc  4) mingw-w64-x86_64-gcc-ada  5) mingw-w64-x86_64-gcc-fortran  6) mingw-w64-x86_64-gcc-libgfortran  7) mingw-w64-x86_64-gcc-libs  8) mingw-w64-x86_64-gcc-objc  9) mingw-w64-x86_64-gdb  10) mingw-w64-x86_64-headers-git  11) mingw-w64-x86_64-libmangle-git  12) mingw-w64-x86_64-libwinpthread-git  13) mingw-w64-x86_64-make  14) mingw-w64-x86_64-pkg-config  15) mingw-w64-x86_64-tools-git  16) mingw-w64-x86_64-winpthreads-git  17) mingw-w64-x86_64-winstorecompat-git
L&#246;se Abh&#228;ngigkeiten auf...
Suche nach in Konflikt stehenden Paketen...
<span class="function-name">Warnung</span>: Abh&#228;ngigkeits-Zyklus entdeckt:
<span class="function-name">Warnung</span>: mingw-w64-x86_64-harfbuzz wird vor seiner Abh&#228;ngigkeit mingw-w64-x86_64-freetype installiert werden

Pakete (29) mingw-w64-x86_64-brotli-1.0.3-1  mingw-w64-x86_64-c-ares-1.13.0-4  mingw-w64-x86_64-cairo-1.15.12-1  mingw-w64-x86_64-curl-7.59.0-2  mingw-w64-x86_64-fontconfig-2.13.0-1  mingw-w64-x86_64-freetype-2.9-1  mingw-w64-x86_64-glib2-2.56.1-1  mingw-w64-x86_64-graphite2-1.3.11-1  mingw-w64-x86_64-harfbuzz-1.7.5-2  mingw-w64-x86_64-icu-61.1-1  mingw-w64-x86_64-jansson-2.10-1  mingw-w64-x86_64-lcms2-2.8-1  mingw-w64-x86_64-libidn2-2.0.4-1  mingw-w64-x86_64-libjpeg-turbo-1.5.3-1  mingw-w64-x86_64-libmetalink-0.1.3-3  mingw-w64-x86_64-libssh2-1.8.0-1  mingw-w64-x86_64-libtiff-4.0.9-1  mingw-w64-x86_64-libunistring-0.9.8-1  mingw-w64-x86_64-lzo2-2.10-1  mingw-w64-x86_64-nghttp2-1.31.0-1  mingw-w64-x86_64-nspr-4.19-1  mingw-w64-x86_64-nss-3.36.1-1  mingw-w64-x86_64-openjpeg2-2.3.0-1  mingw-w64-x86_64-pcre-8.42-1  mingw-w64-x86_64-pixman-0.34.0-3  mingw-w64-x86_64-poppler-data-0.4.8-1  mingw-w64-x86_64-wineditline-2.201-1  mingw-w64-x86_64-libpng-1.6.34-1  mingw-w64-x86_64-poppler-0.63.0-2

Gesamtgr&#246;&#223;e des Downloads:            35,08 MiB
Gesamtgr&#246;&#223;e der installierten Pakete:  212,04 MiB

<span class="comint-highlight-prompt"><span class="comint-highlight-prompt">:: Installation fortsetzen? [J/n] </span></span><span class="comint-highlight-input">J</span>
J
:: Empfange Pakete...
Lade mingw-w64-x86_64-libpng-1.6.34-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-wineditline-2.201-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-pcre-8.42-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-glib2-2.56.1-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-graphite2-1.3.11-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-harfbuzz-1.7.5-2-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-freetype-2.9-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-fontconfig-2.13.0-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-lzo2-2.10-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-pixman-0.34.0-3-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-cairo-1.15.12-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-c-ares-1.13.0-4-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-brotli-1.0.3-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-libunistring-0.9.8-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-libidn2-2.0.4-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-libmetalink-0.1.3-3-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-libssh2-1.8.0-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-jansson-2.10-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-nghttp2-1.31.0-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-curl-7.59.0-2-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-icu-61.1-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-icu-61.1-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-icu-61.1-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-icu-61.1-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-icu-61.1-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-libjpeg-turbo-1.5.3-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-libtiff-4.0.9-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-lcms2-2.8-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-nspr-4.19-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-nss-3.36.1-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-openjpeg2-2.3.0-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-poppler-data-0.4.8-1-any.pkg.tar.xz herunter...
Lade mingw-w64-x86_64-poppler-0.63.0-2-any.pkg.tar.xz herunter...
Pr&#252;fe Schl&#252;sselring...
Pr&#252;fe Paketintegrit&#228;t...
Lade Paket-Dateien...
Pr&#252;fe auf Dateikonflikte...
&#220;berpr&#252;fe verf&#252;gbaren Festplattenspeicher...
:: Verarbeite Paket&#228;nderungen...
Installiere mingw-w64-x86_64-libpng...
Installiere mingw-w64-x86_64-wineditline...
Installiere mingw-w64-x86_64-pcre...
Installiere mingw-w64-x86_64-glib2...
Keine Schema-Dateien gefunden: Nichts wird getan.
Installiere mingw-w64-x86_64-graphite2...
Installiere mingw-w64-x86_64-harfbuzz...
Optionale Abh&#228;ngigkeiten f&#252;r mingw-w64-x86_64-harfbuzz
    mingw-w64-x86_64-icu: harfbuzz-icu support [ausstehend]
    mingw-w64-x86_64-cairo: hb-view program [ausstehend]
Installiere mingw-w64-x86_64-freetype...
Installiere mingw-w64-x86_64-fontconfig...

  Fontconfig configuration is done via /mingw64/etc/fonts/conf.avail and conf.d.
  Read /mingw64/etc/fonts/conf.d/README for more information.

updating font cache... done.
Installiere mingw-w64-x86_64-lzo2...
Installiere mingw-w64-x86_64-pixman...
Installiere mingw-w64-x86_64-cairo...
Optionale Abh&#228;ngigkeiten f&#252;r mingw-w64-x86_64-cairo
    mingw-w64-x86_64-glib2: libcairo-gobject [Installiert]
Installiere mingw-w64-x86_64-c-ares...
Installiere mingw-w64-x86_64-brotli...
Installiere mingw-w64-x86_64-libunistring...
Installiere mingw-w64-x86_64-libidn2...
Installiere mingw-w64-x86_64-libmetalink...
Installiere mingw-w64-x86_64-libssh2...
Installiere mingw-w64-x86_64-jansson...
Installiere mingw-w64-x86_64-nghttp2...
Installiere mingw-w64-x86_64-curl...
Installiere mingw-w64-x86_64-icu...
Installiere mingw-w64-x86_64-libjpeg-turbo...
Installiere mingw-w64-x86_64-libtiff...
Installiere mingw-w64-x86_64-lcms2...
Installiere mingw-w64-x86_64-nspr...
Installiere mingw-w64-x86_64-nss...
Installiere mingw-w64-x86_64-openjpeg2...
Installiere mingw-w64-x86_64-poppler-data...
Installiere mingw-w64-x86_64-poppler...
Optionale Abh&#228;ngigkeiten f&#252;r mingw-w64-x86_64-poppler
    mingw-w64-x86_64-glib2: libpoppler-glib [Installiert]
    mingw-w64-x86_64-qt5: libpoppler-qt5

---------------------------
 Configuring and compiling 
---------------------------
autoreconf -i
<span class="function-name">configure.ac</span>:15: installing './ar-lib'
<span class="function-name">configure.ac</span>:11: installing './compile'
<span class="function-name">configure.ac</span>:78: installing './config.guess'
<span class="function-name">configure.ac</span>:78: installing './config.sub'
<span class="function-name">configure.ac</span>:6: installing './install-sh'
<span class="function-name">configure.ac</span>:6: installing './missing'
<span class="function-name">Makefile.am</span>: installing './depcomp'
./configure -q --bindir=c:/!Software/Portable/Emacs/bin/ &amp;&amp; make -s

Is case-sensitive searching enabled ?     yes
Is modifying text annotations enabled ?   yes
Is modifying markup annotations enabled ? yes


---------------------------
       Installing          
---------------------------
make -s install
<span class="function-name">make</span>[<span class="compilation-line-number">1</span>]: Verzeichnis &#8222;/c/!Data/home/jlange/.emacs.d/elpa/pdf-tools-20180422.935/build/server&#8220; wird betreten
 /usr/bin/mkdir -p 'c:/!Software/Portable/Emacs/bin'
  /usr/bin/install -c epdfinfo.exe 'c:/!Software/Portable/Emacs/bin'
<span class="function-name">make</span>[<span class="compilation-line-number">1</span>]: F&#252;r das Ziel &#8222;install-data-am&#8220; ist nichts zu tun.
<span class="function-name">make</span>[<span class="compilation-line-number">1</span>]: Verzeichnis &#8222;/c/!Data/home/jlange/.emacs.d/elpa/pdf-tools-20180422.935/build/server&#8220; wird verlassen
<span class="function-name">cp</span>: regul&#228;re Datei 'c:/!Software/Portable/Emacs/bin/libwinpthread-1.dll' kann nicht angelegt werden: Device or resource busy
<span class="function-name">cp</span>: regul&#228;re Datei 'c:/!Software/Portable/Emacs/bin/libgcc_s_seh-1.dll' kann nicht angelegt werden: Device or resource busy
<span class="function-name">cp</span>: regul&#228;re Datei 'c:/!Software/Portable/Emacs/bin/libintl-8.dll' kann nicht angelegt werden: Device or resource busy
<span class="function-name">cp</span>: regul&#228;re Datei 'c:/!Software/Portable/Emacs/bin/libunistring-2.dll' kann nicht angelegt werden: Device or resource busy

===========================
   Build succeeded. :O)    
===========================

Comint finished at Tue Apr 24 04:06:01
</pre>
  </body>
</html>

#+END_SRC

#+RESULTS:
[[file:pdf-tools.pdf]]

* Installation Instructions
** Windows Registration
*** Save as .reg files and execute once
**** Register-Emacs-Client.reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\openWithEmacs]
@="&Edit with Emacs"
"icon"=%EMACS%\\bin\\Emacsclientw.exe"

[HKEY_CLASSES_ROOT\*\shell\openWithEmacs\command]
@="\"%EMACS%\\bin\\emacsclientw.exe\" -a \"\" -n \"%L\""
**** Register-Emacs-file-type.reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\EmacsFile]
@="EmacsFile"

[HKEY_CLASSES_ROOT\EmacsFile\DefaultIcon]
@="%EMACS%\\bin\\emacsclientw.exe,0"

[HKEY_CLASSES_ROOT\EmacsFile\shell\open]
@="Open in Emacs"

[HKEY_CLASSES_ROOT\EmacsFile\shell\open\command]
@="\"%EMACS%\\bin\\emacsclientw.exe\" -a \"\" -n \"%L\""
**** Register-extensions-to-emacs.reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.el]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.org]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.properties]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.diff]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.cfg]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.cpp]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.css]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.conf]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.log]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.sh]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.ses]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.txt]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.md]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.sgm]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.key]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.pem]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.csr]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.req]
@="EmacsFile"
"Content Type"="text/plain"
"PerceivedType"="text"
**** Register-the-Outlook-URL-Handler.reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\outlook]
@="URL:Outlook Folders"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\outlook\DefaultIcon]
@="%OUTLOOK4E%\\OUTLOOK.EXE"

[HKEY_CLASSES_ROOT\outlook\shell]

[HKEY_CLASSES_ROOT\outlook\shell\open]

[HKEY_CLASSES_ROOT\outlook\shell\open\command]
@="\"%OUTLOOK4E%\\OUTLOOK.EXE\" /select \"%1\""
**** Org Protocol
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\org-protocol]
@="URL:Org Protocol"
"URL Protocol"=""
[HKEY_CLASSES_ROOT\org-protocol\shell]
[HKEY_CLASSES_ROOT\org-protocol\shell\open]
[HKEY_CLASSES_ROOT\org-protocol\shell\open\command]
@="\"C:\\!Software\\Portable\\Emacs\\bin\\emacsclientw.exe\" \"%1\""
**** Fix-RDP-Cursorblink.reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server]
"CursorBlinkEnable"=dword:00000001
*** Use-Google-Maps-in-Outlook-2010-Contacts.reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Outlook\Options\General]
"MapScriptURL"="http://maps.google.com/?q=<0s>, <1s>, <2s>, <3s>, <4s>"
** Download and install current version of
*** Dig
Modern DNS-Query Tool
http://ftp.isc.org/isc/bind9/cur/
Install with "Tools only" option
*** Ditaa
**** Purpose and General-Information
- Diagramm Creator from Text
**** Download and Installation
- https://github.com/stathissideris/ditaa
- Download and unzip latest version to a folder
- Set Path in specific.org
- This app requires Java Runtime installed
*** Fakecygpty
**** Purpose and General-Information
Fixes shell problems in emacs when shell is based on mintty running on MSYS2 or Cygwin
**** Download and Installation
- Download fakecygpty from https://github.com/d5884/fakecygpty
- Compile using the command autoreconf -ivf && ./configure && make install
- copy fakecygpty.el into ~/.emacs.d/myscripts/
- evaluate (fakecygpty-activate) via use-package
*** Ghostscript 64bit
**** Purpose and General-Information
- Postscript suite required to enable postscipt processing for printing produced by emacs and it's packages.
- Can produce pdfs from postscript
**** Download and Installation
- https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/
- Download gsXXXw64.exe
- Install in C:/Program Files/gs/ not C:/Program Files/gs/gsXX.XX/ This avoids reconfiguration after update
*** Gnuplot
**** Purpose and General-Information
Ability to create graphs from data as file or directly to display.
**** Download and Installation
- Download Portable version from https://sourceforge.net/projects/gnuplot/files/gnuplot/
- Add Path to User-PATH
- Download both gnuplot and gnuplot-mode from melpa. See instructions in config file for gnuplot.
*** Graphviz
**** Purpose and General-Information
- Required for org-mind-map
**** Download and Installation
- http://graphviz.org/Download_windows.php
- Download graphviz-X.XX.msi
- Install executable under .../Graphviz/ not /.../GraphvizX.XX//
- add ...\Graphviz\bin to your PATH variable
*** ImageMagick
**** Purpose and General-Information
- Allows Image Dired Thumbnail Mode to work
**** Download and installation
- Do NOT download ImageMagick 7.X since it is not yet supported in Emacs. 6.X is still supported by ImageMagick. Unofficial Emax64 contains ImageMagick 7.
- Source https://www.imagemagick.org/download/binaries/ImageMagick-6.9.X-X-Q16-x64-dll.exe
- Install without any options, except adding path the System PATH
*** Miktex 64bit
**** Purpose and General-Information
- Tex-Environment required in order to process latex produced by org mode and other packages.
**** Download and Installation
- http://miktex.org/download
- Download basic-miktex-X.X.XXXX-x64.exe
- Select "Install missing packages on the fly" during installation
- Export an org file once as pdf in order to download the additional needed files  C-c C-e l o
*** MSYS2 64bit
**** Purpose and General-Information
- To have latest unix-tools in 64bit
- Library-numbers might increase over time
- Remove a package and unneeded dependencies execute pacman -Rs PACKAGENAME
- Updates of all installed pacakages have to be done manually by executing "pacman -Syuu" again
**** Download and Installation
- Source http://www.msys2.org/
- Download latest msys2-x86_64-XXXXXXXX.exe
- Default Installation then open a mintty terminal and execute "pacman -Syuu"
- Kill the terminal, NOT by executing "exit" rather than by pressing the X button on the window
- Execute "pacman -Syuu" again
- Execute "pacman -S tmux fish zsh zsh-doc screenfetch pwgen tree compression net-utils inetutils gnu-netcat whois mingw-w64-x86_64-hunspell mingw-w64-x86_64-hunspell-en base-devel mingw-w64-x86_64-toolchain msys2-devel sys-utils" to add extra-packages mentioned below
- Add C:\msys64\mingw64\bin and C:\msys64\usr\bin to your PATH variable in this order
- Reboot after all packages were installed, this should make sure all environment variables get set correctly
- Execute "updatedb" for the locate program to work correctly add a windows task to the scheduler that this is done daily containing Z:\Tools\cygwin64\bin\mintty.exe -e 'updatedb -localpaths='//z// //c//'
- copy default settings files like .bashrc from ? to your home directory
- still missing: bind-utils (dig), ipcalc, hunspell-de
***** add variables below to .bashrc inside your home directory
#
# Set Language
export LANG=de_DE.UTF-8
export LC_ALL=de_DE.UTF-8
#
# Set Prompt
PS1="\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$"
#
# Avoid duplicates in history
export HISTCONTROL=ignoredups:erasedups
#
# VIM Alias
alias vi=vim
***** Checking
You can check with "locale" command the locale environment variables and with env the other variables
***** Extra-Packages Details
****** Compression
required for some packages to extract downloaded content
****** Clang
Installs C++ Compiler
****** Git
version control
****** Programming
base-devel - all tools required for compiling. Some packages need to compile files.
python - python
libcrypt-devel - required for installing pylint via pip
****** Python3 pip3 - python package installer
******* Update Pip3 and basic packages
pip3 install --trusted-host pypi.org --trusted-host files.pythonhosted.org --upgrade pip setuptools wheel
******* Install a package
pip3 install --trusted-host pypi.org --trusted-host files.pythonhosted.org PACKAGENAME
******* List installed packaes
pip3 list
******* List outdated packages
pip3 list --trusted-host pypi.org --trusted-host files.pythonhosted.org --outdated
******* Upgrade packages
pip3 install --trusted-host pypi.org --trusted-host files.pythonhosted.org --upgrade PACKAGENAME
******* Recommended Packages
- td-watson
- pylint
- proselint
****** Inetutils
inetutils containing telnet(d), ftp(d), talk(d), tftp(d), uucpd, sylogd
****** Netcat
nc command to test connections
****** Openssh
openssh - standard ssh client and server
****** RSync
rsync - standard program to sync files
****** Shells
fish
Edit /etc/fish/fish.conf in the same way as .bashrc mentioned above
******* zsh - Oh-my-zsh
Website: https://github.com/robbyrussell/oh-my-zsh
Download Oh-my-Zsh via curl from the URL below
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
****** Spellchecking
- hunspell - most current spellchecker available
- Hunspell requires the setting of the DICPATH environment variable in Windows, otherwise dictionaries won't be found by emacs. See specific.org
- huspell-de is missing download the latest dict from libre-office extensions repository https://extensions.libreoffice.org/extensions/german-de-de-frami-dictionaries and installed the .dic and .aff files into C:\msys64\mingw64\share\myspell\dicts
- huspell-fr is missing download the latest dict from libre-office extensions repository https://extensions.libreoffice.org/extensions/dictionnaires-francais/5.7 and installed the .dic and .aff files into C:\msys64\mingw64\share\myspell\dicts
****** Terminal Multiplexing
tmux
******* Start mintty using this command
C:\msys64\usr\bin\mintty.exe -e 'Z:\home\jlange\start-tmux.sh' -
******* start-tmux.sh
#!/bin/fish
tmux
******* .tmux.conf (Save file in Unix-Format, otherwise CRLF might not be interpreted correcty)
# Window-Switching without prefix
bind-key -n S-Left previous-window
bind-key -n S-Right next-window

# Pane-Switching without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Activate mouse (Causes font resize using C+mouse-wheel to stop working, CS+mouse-wheel still works)
set -g mouse on

# Show information in title-bar
set -g set-titles on

# Set Terminal to use 256 colors
set -g default-terminal "screen-256color"

# Statusbar/window configuration
set -g status-interval 1
set -g status-attr bright
set -g status-fg white
set -g status-bg colour240
set -g status-justify centre
set -g status-left '#[fg=green][#[fg=red]#S#[fg=green]]#[default]'
set -g status-right '#[fg=green][#[fg=colour214]%d.%m.%y %H:%M:%S#[fg=green]]#[default]'
setw -g window-status-current-format '#[fg=green](#[fg=yellow]#I.#P#F#W#[fg=green])#[default]'
setw -g window-status-format '#I#F#W'
****** Version-Control
ca-certificates - required for ssl operations
****** Vim - Test vim commands locally if needed
vim - needs to be called by executing "vim" not "vi" if no alias is defined
****** Whois
whois - standard tool to lookup domains
****** Zip
not part of compression, required for odt export 
**** Adding your windows user to cygwin and setting home, which also sets the HOME variable based on the user
***** Execute following commands in cygwin terminal:
mkgroup > /etc/group
mkpasswd -cl > /etc/passwd
***** Check
Open /etc/passwd check that you username was added
***** Set absolute cygwin path and change default shell
edit /etc/passwd file and change /bash to /fish or /zsh
**** Improve git speed, in Windows by executing
git config --global core.fscache true
**** Configuration files
Copy configuration file templates to the home folder. They are located in /etc/skel
**** Add string below to (HOME-Directory)\.ssh\config in order to avoid problems when using a local proxying application which connects to different hosts using localhost
Host 127.0.0.*
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null
**** Inherit the PATH
uncomment in mingw64 .ini the inherit path line
**** Setup SSH
- Execute in terminal: ssh-keygen
- This sets up basic ssh configuration and creates folders and files
*** Notpad++
This might look strange, but in case of an emergency, i.e. Emacs is not starting up, this editor might save the day.
https://notepad-plus-plus.org/
*** NT-Emacs 64bit
**** Emacs
***** Purpose and General-Information
- Editor itself
***** Download and Installation
https://ftp.gnu.org/gnu/emacs/windows/emacs-XX.X-x86_64-w64-mingw32.zip
https://ftp.gnu.org/gnu/emacs/windows/emacs-XX-x86_64-deps.zip
- Extract Emacs to dir, then the deps also into it.
- Run /bin/addpm.exe as Adminstrator. Click yes.
*** Pandoc
**** Purpose and General-Information
- Document Converter
**** Download and Installation
- https://github.com/jgm/pandoc/releases/
- Download and install pandoc-X.XX.X-windows.msi
*** PhantomJS
Required for OB-Browser
http://phantomjs.org/download.html
*** Reveal.js
**** Purpose and General-Information
- For visually pleasant presentation export
**** Download and installation
- Source https://github.com/hakimel/reveal.js/releases
- Extract Source to folder named "reveal.js" Put the "reveal.js" folder in the same folder as the presentation.org
- Execute M-x org-reveal-export-to-html to export to html, open manually in Browser
*** Ripgrep
**** Purpose and General-Information
- Fast search through files
**** Download and Installation
- https://github.com/BurntSushi/ripgrep/releases
- Download and unzip latest version to a folder
- Add folder path to PATH variable
*** Sharp-Keys
This app should be used to remap buttons on the OS-Level. Configuations depends on the keyboard used. I recommend:
Capslock to Right-Windows-Keys
Calc to Apps (Apps is the "Menu-Key")
https://github.com/randyrants/sharpkeys
*** Source-Code-Pro-Font
**** Purpose and General-Information
- Better readable default font
**** Download and installation
- Source https://github.com/adobe-fonts/source-code-pro/releases/
- Extract and install in C:\Windows\Fonts
*** Symbola-Font
**** Purpose and General-Information
- Better Unicode Symbol Support
**** Download and installation
- Source http://users.teilar.gr/~g1951d/
- Extract and install in C:\Windows\Fonts

*** WinCompose
This app uses AltGr as a compose key. The compose key allows access to various symbols using a key combination.
https://github.com/samhocevar/wincompose
** Add Putty to the Windows-Environment User PATH-Variables if you want to use the Putty command line tools like plink
*** Location to add
Control Panel\All Control Panel Items\System\Advanced System settings\Environment Variables\User Variables for (YourUsername)
*** Path to add to the PATH varible in location above (Adjust to your installation)
C:\Program Files\Putty\
*** Check
use "env" command to check
** Registration Files
- Save Content of registration files in specific.org in .reg files
- Adjust paths inside reg-file to your installation
- Execute once
** Emacs-Dot-Files
*** init.el (Main-Loader)
- Copy init.el from this archive to ~\.emacs.d\
*** custom.el (Custom-System writes here)
- Copy custom.el from this archive to ~\.emacs.d\
*** configuration.org (Main configuration-File from which configuration.el is generated and then loaded by init.el)
- Put configuration.org file in ~\org\active\ (Create neccessary folders)
*** specific.org (Additional configuration-File from which specific.el is generated and then loaded by init.el)
- Put specific.org file also in ~\org\active\
- Edit to your needs, since it contains installations-specific configuration parts
** Other Instructions
- Open %windir%\system32\SystemPropertiesPerformance.exe and disable "Animate windows when mini...", this also disables the Switch virtual Desktop animation
- Keycords involving Alt-Gr, like "C-M \" (region-intent) require you to use the right control key in order to work
- The package use-packages installs the required packages after it installed itself and its requirements though the boostrap code.
- Reboot after first completion of steps above
- If org files look that is something missing, mostly after loading, just fold and unfold at top level
- Create all the files in Org folder that are mentioned in the .emacs
- Create diary file in your home dir, not in .emacs.d dir
- Uncomment debug on error if needed
- You can run profiler start and profiler report, profiler stop for a comprehensive list of functions that were called. Press d in the report to get the definition.
- Take ownership of ~/emacs.d/server . Adminstrator->YourUser . Otherwise you get errors at server-start.
- If desktop is not loaded check home for .emacs.desktop.lock file and delete it (when emacs is not running)
- Be sure your user is direct owner of the home directory and all subfiles/subdirectories. Otherwise the client may not start.
** Known issues/broken stuff
*** Remote-Terminals
- Mostly broken, the implementation of terminals in emacs is geared towards a POSIX system and not towards windows. Don't waste your time. A reimplementation is not in sight.
- Workaround: Use standard putty or kitty, for file transfer use win-scp
*** Shells
- shell is not a 1-to-1 output of the mintty. Remote access started via shell is broken, requires fakecygpty to fix and still has problems sending interrupt signals like C-c
- Workaround: Start a mintty directly from windows
- To this date [2017-12-21 Do] powershell can not be used as an emacs shell, see powershell package description
*** Unused popular Packages
**** Projectile
Since I work with org mode and org-links to the project directories, which open up the windows-explorer I have no need for projectile
**** Dired
I use the Windows-Explorer, it's integration with windows is obviously seemless for local or remote files.
**** Tramp
I rarely need to edit files remotely, if so it's in most cases a one-liner which is done using vi, additional shells on windows are mostly broken and remote access to files is very slow
** Basic Github Configuration
(Open Mintty, then)
git config --global user.email "myusername@myemailprovider.com"
git config --global user.name "My Name"
git config credential.https://github.com.username githubusername
git config --global credential.helper store
git remote add origin https://github.com/githubusername/yourrepositoryname.git
git push -u origin master
Password for 'https://githubusername@github.com':XXXXXXXXXXXX
git remote -v
